language: rust
cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libbfd-dev

before_script: |
  PKGNAME="wfc-rust" # must match with cargo.toml
  LOCAL="~/.local" # install here to avoid `sudo`
  export PATH=$LOCAL/bin:$PATH

after_success: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
      tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
      cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && make &&
      make install && cd ../.. &&

      kcov --verify \
           --coveralls-id=$TRAVIS_JOB_ID \
           --exclude-pattern=/.cargo \
           target/kcov target/debug/$PKGNAME-*
  fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

notifications:
  email:
    recipients:
      - declankolakowski@gmail.com
      - marcus.desai@gmail.com
    on_success: change
    on_failure: always
