[package]
name = "wfc-rust"
version = "0.1.0"
authors = ["dpwdec <declankolakowski@gmail.com>", "Marcus Desai <marcus.desai@gmail.com>"]
edition = "2018"
repository = "https://github.com/SaiskiFunctions/GraphWFC.rs"

[badges]
travis-ci = { repository = "...", branch = "master" }
coveralls = { repository = "...", branch = "master", service = "github" }

[dependencies]
rand = "0.7.3"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "collapse"
harness = false
