[package]
name = "wfc-rust"
version = "0.1.0"
authors = ["dpwdec <declankolakowski@gmail.com>", "Marcus Desai <marcus.desai@gmail.com>"]
edition = "2018"
repository = "https://github.com/SaiskiFunctions/GraphWFC.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
nalgebra = "0.21.1"
bencher = "0.1.5"
hashbrown = "0.8.1"

[[bench]]
name = "benches"
harness = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"
incremental = false
codegen-units = 1
rpath = false
